[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
stopwatch = "0.0.7"
aoc_lib = {path = "aoc_lib"}
log = "0.4.20"
geo = "0.27.0"